/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FormHeader: typeof import('./src/components/FormHeader.vue')['default']
    ShowImg: typeof import('./src/components/ShowImg.vue')['default']
    ShowModal: typeof import('./src/components/ShowModal.vue')['default']
    Test: typeof import('./src/components/test.vue')['default']
  }
}
